package test.assertk

actual val exceptionPackageName: String = ""
